[package]
name = "choux"
version = "0.1.0-rc.1"
description = "Native client for ptys"
authors = ["Karol Nowacki"]
license = "MIT"
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "choux_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
futures-util = "0.3"
keyring = "4.1.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-deep-link = "2"
tauri-plugin-opener = "2.5.4"
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }
tokio = { version = "1", features = ["macros", "net", "sync"] }
tokio-tungstenite = "0.24"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
